spring:
  datasource:
    url: jdbc:h2:mem:gergs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
  security:
    user:
      name: admin
      password: admin
api:
  endpoint:
    base-url: /api/v1